webrtc:
  key: 720d30e5-edb8-4af5-be35-28051c80e314  #Your SkyWay API key
  config: #未使用
    iceServers: #未使用
      - url: stun:stun.skyway.io:3478
      - url: turn:homeo@turn.bistri.com:80
        credential: homeo
password:
 pass: MegaHeracross
dice: #未使用
